name: FinnehSpoof
main: com.geminispoofer.GeminiSpoofer
version: 1.1.0
api-version: "1.20"
depend: [ProtocolLib, FinnehCore]
softdepend: [PlaceholderAPI]
commands:
  finnehspoof:
    description: FinnehSpoof control command.
    usage: "/finnehspoof <help|reload|enable|disable|relationships>"
permissions:
  geminispoofer.ignore:
    description: Ignore chat logging for this player.
    default: false
